development:
  adapter: postgresql
  encoding: unicode
  database: magniton_db
  username:   <%= ENV['DATABASE_USERNAME'] %>
  password:   <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

test: # this has to be different
  adapter: postgresql
  database: prelaunchr_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: magniton_db
  pool: 5
  username:   <%= ENV['DATABASE_USERNAME'] %>
  password:   <%= ENV['DATABASE_PASSWORD'] %>





